"""autogen vote

Revision ID: 36f8054a78dd
Revises: 638a77c1ec2f
Create Date: 2023-10-01 00:30:17.911077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36f8054a78dd'
down_revision: Union[str, None] = '638a77c1ec2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postsA')
    op.drop_table('usersA')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersA',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"usersA_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usersA_pkey'),
    sa.UniqueConstraint('email', name='usersA_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('postsA',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"postsA_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['usersA.id'], name='postA_users_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='postsA_pkey')
    )
    # ### end Alembic commands ###
